#!/usr/bin/env bash

# this is a simple config for herbstluftwm
TERM=${TERMINAL:-gnome-terminal}
ENABLE_DUALHEAD="$(realpath ~/.config/herbstluftwm/dualhead)"
xsetroot -solid '#000000'


hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

#hc keybind $Mod-Shift-q quit
hc keybind $Mod-Control-q close
hc keybind $Mod-Control-e quit
hc keybind $Mod-Control-r reload
hc keybind $Mod-Control-w close
hc keybind $Mod-Return spawn ${TERM} # use your $TERMINAL with xterm as fallback
hc keybind $Mod-Shift-Return spawn ${TERM} -e 'bash -c "tmux new-session -t 0 || tmux"'

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-i       split   bottom  0.5
hc keybind $Mod-v       split   right   0.5
hc keybind $Mod-o		split	auto

# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# cycle through tags
hc keybind $Mod-comma use_index -1 --skip-visible
hc keybind $Mod-period  use_index +1 --skip-visible

# layouting
hc keybind $Mod-Shift-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-space cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# runstuff
hc keybind $Mod-d spawn dmenu_run

# Brigthness
hc keybind XF86MonBrightnessUp spawn sh -c "xbacklight +5"
hc keybind XF86MonBrightnessDown spawn sh -c "xbacklight -5"

# Volume
hc keybind XF86AudioRaiseVolume spawn sh -c "pactl set-sink-mute 0 false ; pactl set-sink-volume 0 +5%"
hc keybind XF86AudioLowerVolume spawn sh -c "pactl set-sink-mute 0 false ; pactl set-sink-volume 0 -5%"
hc keybind XF86AudioMute spawn sh -c "pactl set-sink-mute 0 toggle"

# Misc
#hc keybind Print spawn screenshot
#hc keybind XF86TouchpadToggle spawn touchpad

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#456565'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.active.color '#AFBB6E' #'#8E610E'
hc attr theme.normal.color '#20282c'
hc attr theme.urgent.color orange
hc attr theme.outer_width 1
hc attr theme.inner_color '#20282c'
hc attr theme.border_width 3

hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 2
hc attr theme.floating.outer_color black
hc attr theme.floating.inner_color '#20282c'

hc attr theme.active.inner_color '#8e610e' #8c8c88
hc attr theme.active.outer_color black
hc attr theme.background_color '#141414'

hc set window_gap 3 
hc set frame_padding 0
hc set smart_window_surroundings 0 
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set focus_follows_mouse 0

# tags
#tag_names( term web img herb null foo )
#tag_keys=( {1..6} 0 )

tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# rules
hc unrule -F
hc rule class=Firefox tag=h
hc rule class=Steam tag=t
hc rule focus=on # normally focus new clients

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

hc set tree_style '╾│ ├└╼─┐'


#running most useful tmux socket
tmux -S /tmp/$USER.tmux new -s shared

#setting default screen
hc set_monitors 1920x1080+0+0

# cat pic ftw
xli -border black -onroot -display ":0" -fillscreen  ~/.config/herbstluftwm/cat_pic.jpg
compton -b -d :0

# find the panel
panel=~/.config/herbstluftwm/panel
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done
